### ISSUE TITLE
Missing description under title

### ISSUE THREAD

**Issue by lfarah** [bernikowich/NSTEasyJSON#1]
![screen shot 2016-12-16 at 15 24 16](https://cloud.githubusercontent.com/assets/6511079/21281702/bfd3a8ce-c3a3-11e6-93a8-754e992ab51a.png)

**Comment by lfarah** [comment]
https://github.com/vsouza/awesome-ios/pull/1347

**Comment by bernikovich** [comment]
Fixed.
