### ISSUE TITLE
Useful stability fix

### ISSUE THREAD

**Issue by duke4e** [bernikowich/NSTEasyJSON#4]
Hi,

I'm using your great library and it looks like that the data I'm getting from server can be incosistent, so if the server returns no data, the app crashes in "+ (nonnull instancetype)withData:(nullable NSData *)data".

I've made the simple fix for that issue and am sharing it here with you:
    id object = [NSJSONSerialization JSONObjectWithData:data ? data : [NSData data] options:NSJSONReadingAllowFragments error:&error];

**Comment by bernikowich-cedoni** [comment]
@duke4e hello.
Sorry for the late response. Can you create PR please? It will be awesome.

**Comment by bernikovich** [comment]
**Fixed**: https://github.com/bernikowich/NSTEasyJSON/releases/tag/1.0.6
